const OperationType = {
  REGISTRATION: "REGISTRATION",
  UNREGISTRATION: "UNREGISTRATION",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SUBSCRIBE_NOTIFICATION: "SUBSCRIBE_NOTIFICATION",
  UNSUBSCRIBE_NOTIFICATION: "UNSUBSCRIBE_NOTIFICATION",
  SET_FAVOURITE_PARKING_SPOT: "SET_FAVOURITE_PARKING_SPOT",
  EXTERNAL_API_CALL: "EXTERNAL_API_CALL",
  GET_USER_NOTIFICATIONS: "GET_USER_NOTIFICATIONS",
  GET_USER: "GET_USER",
  GET_PARKING_LOT: "GET_PARKING_LOT",
  UPDATE_PROFILE: "GET_USER",
  ACTUAL_STATE_OF_PARKING_LOTS: "ACTUAL_STATE_OF_PARKING_LOTS",
};

module.exports = OperationType;
